# Generated by Django 5.0.4 on 2024-05-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_othercontacts_contacts_city_contacts_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='othercontacts',
            name='image',
            field=models.ImageField(default=1, upload_to='image/', verbose_name='Задний фон'),
            preserve_default=False,
        ),
    ]
