# Generated by Django 5.0.4 on 2024-05-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(help_text='Нужно написать автора блога', max_length=255, verbose_name='Автор')),
                ('date', models.DateField(verbose_name='Дата')),
                ('title', models.CharField(max_length=600, verbose_name='Название блога')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
