# Generated by Django 5.0.4 on 2024-05-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0004_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='publication',
            field=models.TextField(default=1, verbose_name='Публикация'),
            preserve_default=False,
        ),
    ]
