# Generated by Django 5.0.4 on 2024-05-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary', '0013_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('location', models.CharField(max_length=255, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изображение')),
                ('data', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Предстоящее событие',
                'verbose_name_plural': 'Предстоящии событии',
            },
        ),
    ]
