# Generated by Django 5.0.4 on 2024-05-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='settings_logo/', verbose_name='Логотип')),
                ('fullname', models.CharField(max_length=100, verbose_name='ФИО')),
                ('subdescription', models.TextField(verbose_name='Миниописание')),
            ],
            options={
                'verbose_name': 'Основная настройка',
                'verbose_name_plural': 'Основные настройки',
            },
        ),
    ]
