# Generated by Django 5.0.4 on 2024-05-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('minidesc', models.CharField(max_length=255, verbose_name='Миниописание')),
            ],
            options={
                'verbose_name': 'Главное описание',
                'verbose_name_plural': 'Главные описания',
            },
        ),
    ]
