# Generated by Django 5.0.4 on 2024-05-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='title',
            new_name='firsttitle',
        ),
        migrations.RenameField(
            model_name='title',
            old_name='minidesc',
            new_name='subtitle',
        ),
    ]
