# Generated by Django 5.0.4 on 2024-05-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_title_title_firsttitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='firsttitle',
        ),
        migrations.RemoveField(
            model_name='title',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='title',
            name='desc',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='title',
            name='subdesc',
            field=models.CharField(default=1, max_length=255, verbose_name='Второе описание'),
            preserve_default=False,
        ),
    ]
