# Generated by Django 5.0.4 on 2024-05-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_title_firsttitle_remove_title_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Вам нужно написать программу которая ведется у выпускника', max_length=255, verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Программа выпускника',
                'verbose_name_plural': 'Программы выпускника',
            },
        ),
        migrations.CreateModel(
            name='LifelongLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Вам нужно написать программу которая ведется на протяжении всей жизни', max_length=255, verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Обучение всей жизни',
                'verbose_name_plural': 'Обучения всей жизни',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Вам нужно написать программу которая ведется у студента', max_length=255, verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Программа студента',
                'verbose_name_plural': 'Программы студента',
            },
        ),
    ]
