# Generated by Django 5.0.4 on 2024-05-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_graduate_lifelonglearning_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeinCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название студентеческой жизни')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Жизнь в кампусе',
                'verbose_name_plural': 'Жизнь в кампусах',
            },
        ),
    ]
