# Generated by Django 5.0.4 on 2024-05-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_tuitionfees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Описание стипендии')),
            ],
            options={
                'verbose_name': 'Стипендия',
                'verbose_name_plural': 'Стипендии',
            },
        ),
        migrations.RemoveField(
            model_name='tuitionfees',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='tuitionfees',
            name='title',
        ),
        migrations.AlterField(
            model_name='tuitionfees',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Тайтл'),
        ),
        migrations.AlterField(
            model_name='tuitionfees',
            name='subname',
            field=models.CharField(max_length=255, verbose_name='Подтайтл'),
        ),
    ]
