# Generated by Django 5.0.4 on 2024-05-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_history_missionvaluesleft_missionvaluesright'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255, verbose_name='Автор')),
                ('profession', models.CharField(max_length=255, verbose_name='Автор')),
                ('feedback', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото Учителя')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.CreateModel(
            name='OurCampusTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('video', models.URLField(verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Экскурсия по кампусу',
                'verbose_name_plural': 'Экскурсии по кампусу',
            },
        ),
    ]
