# Generated by Django 5.0.4 on 2024-05-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_feedback_ourcampustour'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='imageclient',
            field=models.ImageField(default=1, upload_to='', verbose_name='Фото клиента'),
            preserve_default=False,
        ),
    ]
