# Generated by Django 5.0.4 on 2024-05-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_feedback_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='image',
            field=models.ImageField(upload_to='image/', verbose_name='Фото Учителя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='imageclient',
            field=models.ImageField(upload_to='image/', verbose_name='Фото клиента'),
        ),
    ]
