# Generated by Django 5.0.4 on 2024-05-08 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_feedback_image_alter_feedback_imageclient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnievent',
            options={'verbose_name': 'Мероприятие для студента', 'verbose_name_plural': 'Мероприятия для студентов'},
        ),
    ]
