# Generated by Django 5.0.4 on 2024-05-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_alumnievent_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='subdescription',
        ),
        migrations.AddField(
            model_name='settings',
            name='insta',
            field=models.URLField(default=1, max_length=255, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
