# Generated by Django 5.0.4 on 2024-05-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_settings_subdescription_settings_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='insta',
            field=models.URLField(max_length=255, verbose_name='Инстаграм'),
        ),
    ]
